### ISSUE TITLE
Norminette Opening trace in the Output panel

### ISSUE THREAD

**Issue by 4reha** [dalexhd/42-norminette#3]
<img width="1336" alt="Screen Shot 2021-12-11 at 10 43 18 AM" src="https://user-images.githubusercontent.com/80625058/145672069-42784148-3396-4f89-80dc-095b42b30f44.png">

It's really annoying, I have auto save mode enabled, and when I'm typing.. It just pop ups and distract my focus.
Please fix it, I tried to install old version instead, but it's doesnt work

**Comment by dalexhd** [comment]
Can you send a GIF describing the issue? @4reha

**Comment by Pixailz** [comment]
hello @dalexhd, there is a gif and a "situation" where the bug is triggered, hope this will help

![simplescreenrecorder-2022-02-14_15 57 31](https://user-images.githubusercontent.com/35565530/153888464-b6faaf82-2ab6-4bb1-8b4f-623e0830398b.gif)

**Comment by dalexhd** [comment]
@4reha @Pixailz Hello. it should be fixed after these changes: https://github.com/dalexhd/42ToolKit/pull/587

The vscode extension version is: 6.3.0.
